### ISSUE TITLE
YPTStorage is not working

### ISSUE THREAD

**Issue by angry999** [WWBN/AVideo-Storage#14]
I got this log
[07-Oct-2020 15:23:27 UTC] PHP Fatal error:  Uncaught Error: Class 'PluginTags' not found in /var/www/FLC/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code:11
Stack trace:
#0 /var/www/FLC/objects/plugin.php(211): YPTStorage->getTags()
#1 /var/www/FLC/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /var/www/FLC/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code on line 11

**Comment by DanielnetoDotCom** [comment]
Hi

You must update your streamer to the latest version 

Check here https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by angry999** [comment]
Hello
My version is 9.4 and latest version is 9.5
Should I update it?

**Comment by DanielnetoDotCom** [comment]
Yes please

**Comment by angry999** [comment]
Hi, it works after update the version. Thank you
But after I move the storage, it shows the success message and he video files are uploaded correctly.
But when I click the video, it shows this error message. 
"The media could not be loaded, either because the server or network failed or because the format is not supported."

**Comment by DanielnetoDotCom** [comment]
Is your site https? is also your storage https?

can you inspect the code and check the video source file?

can you check if the URL is accessible?
